name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
    - name: Deploy
      run: ./deploy.sh

  post:
    runs-on: ubuntu-latest
    needs: [build, deploy]

    steps:
    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: JAR Files
        path: '**/target/*.jar'

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: 'reports/**/*.xml'

    - name: Notify Success
      if: success()
      run: echo 'Pipeline succeeded!'

    - name: Notify Failure
      if: failure()
      run: echo 'Pipeline failed.'