name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh

    - name: Deploy
      run: ./deploy.sh

    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    - name: Notify Success
      if: success()
      run: echo 'Pipeline succeeded!'

    - name: Notify Failure
      if: failure()
      run: echo 'Pipeline failed.'