name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: |
          if [[ ! -f ./build.sh ]]; then
            echo "Error: build.sh not found. Please ensure it's in the repository root."
            exit 1
          fi

          if [[ ! -x ./build.sh ]]; then
            echo "Error: build.sh is not executable. Please make it executable."
            exit 1
          fi

          ./build.sh
          ./test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
      - name: Ensure Build Artifacts
        run: ls -la ./build

      - name: Deploy
        run: ./deploy.sh

  post:
    runs-on: ubuntu-latest
    needs: [build, deploy]

    steps:
      - name: Archive Artifacts and Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            **/target/*.jar
            reports/**/*.xml

      - name: Notify Result
        if: always()
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "Pipeline succeeded!"
          else
            echo "Pipeline failed."
          fi
