name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Debug: List Files
        run: ls -la

      - name: Build and Test
        run: |
          # Check for script existence and permissions
          if [[ ! -f ./build.sh || ! -x ./build.sh ]]; then
            echo "Error: build.sh not found or not executable!"
            exit 1
          fi

          if [[ ! -f ./test.sh || ! -x ./test.sh ]]; then
            echo "Error: test.sh not found or not executable!"
            exit 1
          fi

          # Explicitly use bash
          bash ./build.sh
          bash ./test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Ensure Build Artifacts
        run: |
          if [[ ! -d ./build ]]; then
            echo "Error: Build directory does not exist!"
            exit 1
          fi
          ls -la ./build

      - name: Deploy
        run: |
          if [[ ! -f ./deploy.sh || ! -x ./deploy.sh ]]; then
            echo "Error: deploy.sh not found or not executable!"
            exit 1
          fi
          bash ./deploy.sh

  post:
    runs-on: ubuntu-latest
    needs: [build, deploy]

    steps:
      - name: Archive Artifacts and Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            **/target/*.jar
            reports/**/*.xml

      - name: Notify Result
        if: always()
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "Pipeline succeeded!"
          else
            echo "Pipeline failed."
          fi
