name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Checkout code is necessary to fetch the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Build step to compile the project
    - name: Build
      run: ./build.sh

    # Optimization: Test step to run the test suite
    - name: Test
      run: ./test.sh

    # Optimization: Deploy step to deploy the application
    - name: Deploy
      run: ./deploy.sh

    # Optimization: Archive build artifacts for future reference or use
    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    # Optimization: Publish test results for visibility and debugging
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    # Optimization: Notify success only if the pipeline succeeds
    - name: Notify Success
      if: success()
      run: echo 'Pipeline succeeded!'

    # Optimization: Notify failure only if the pipeline fails
    - name: Notify Failure
      if: failure()
      run: echo 'Pipeline failed.'