name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Using the latest version of checkout action
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combining build and test steps to reduce overhead
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Using a single artifact upload step to reduce redundancy
    - name: Archive Artifacts and Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-and-test-artifacts
        path: |
          '**/target/*.jar'
          'reports/**/*.xml'

    # Optimization: Combining success and failure messages into one step
    - name: Post Pipeline Status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!';
        else
          echo 'Pipeline failed.';
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Using the latest version of checkout action
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: ./deploy.sh